Program EXERCICIO_06 ;
VAR
PASS : INTEGER;
Begin
WRITE ('DIGITE A SENHA "APENAS NUMEROS": ');
READLN (PASS);
IF (PASS = 1234)
THEN WRITELN ('ACESSO PERMITIDO')
ELSE WRITELN ('ACESSO NEGADO');
READKEY  
End.