Program EXERCICIO_02 ;

VAR
	N1, N2: integer;

Begin

	WRITELN ('DIGITE O PRIMEIRO NUMERO:' );
	READ (N1);
	WRITELN ('DIGITE O SEGUNDO NUMERO:' );
	READ (N2);
	IF (N1>N2)
	THEN WRITELN ('O MAIOR VALOR É O:', N1)
	ELSE WRITELN ('O MAIOR VALOR É O:', N2);
	READKEY
	
End.