PROGRAM TRABALHO;
			//DADOS DO PRODUTO
TYPE
	CAD_PRODUTO = RECORD
									NOME : STRING ;
									QUANTIDADE : INTEGER ;
									VALOR : REAL ;
								END;
	//CONSTANTE PARA OS FORs
CONST MAX = 1;  {VALOR 1 USADO APENAS PARA TESTE}
	//VARIAVEIS GLOBAIS
VAR 
	PRODUTO : ARRAY [1..10] OF CAD_PRODUTO;
	TOTAL_PRODUTO, FAZER, MIN : INTEGER;
	TOTAL_COMPRA, TOTAL_PAGO : REAL;
   //CADSTRO DE PRODUTO
PROCEDURE CADASTRO;
	BEGIN
		MIN := 1;
		FOR MIN := 1 TO MAX DO
		BEGIN
			WRITE ('NOME DO PRODUTO: ');
			READLN (PRODUTO[MIN].NOME);
			WRITE ('QUANTIDADE DO PRODUTO: ');
			READLN (PRODUTO[MIN].QUANTIDADE);
			WRITE ('VALOR UNITARIO DO PRODUTO: R$');
			READLN (PRODUTO[MIN].VALOR);
			CLRSCR;
		END;
	WRITELN ('TECLE <ENTER>'); READKEY;
	END;
  // PROCESSO DE CONSULTA
PROCEDURE CONSULTA;
	VAR I : INTEGER;
	BEGIN
		I := 1;
		FOR I := 1 TO MIN DO
				WRITELN ('PRODUTO: ',PRODUTO[I].NOME);
		WRITELN ('TECLE <ENTER>'); READKEY;
	END;
   // PROCESSAO DE COMPRA
PROCEDURE COMPRA;
	VAR I : INTEGER;
	BEGIN
		I := 1;
		WRITELN ('MENU COMPRA');
		FOR I := 1 TO MIN DO
		BEGIN
			WRITELN (I,' - PRODUTO: ',PRODUTO[I].NOME, ' VALOR: ', PRODUTO[I].VALOR:3:2);
		END;
		WRITELN ('ESCOLHA UM PRODUTO');
		READLN (I);
		TOTAL_COMPRA := TOTAL_COMPRA + PRODUTO[I].VALOR;
		PRODUTO[I].QUANTIDADE := PRODUTO[I].QUANTIDADE - 1;
		WRITELN ('TECLE <ENTER>'); READKEY;
	END;
	//VALOR TOTAL DA COMPRA
PROCEDURE TOTALCOMPRA;
	BEGIN
		WRITE ('O TOTAL DA SUA COMPRA É DE : R$', TOTAL_COMPRA:4:2);
		WRITELN ('TECLE <ENTER>'); READKEY;
	END;
	//FUNÇÃO PARA TROCO
PROCEDURE TROCO;
	VAR Z : REAL;
	BEGIN
	  WRITE ('VALOR PAGO: ');
		READLN (TOTAL_PAGO);
		Z :=  TOTAL_PAGO - TOTAL_COMPRA;
		IF (TOTAL_PAGO < TOTAL_COMPRA) THEN
		WRITELN ('FALTA O VALOR DE',  Z)		
		ELSE
		WRITELN ('TROCO ', Z:2:2);
		WRITELN ('TECLE <ENTER>'); READKEY;
	END;
	// VERIFICAR ESTOQUE
PROCEDURE ESTOQUE;
	VAR I : INTEGER;
	BEGIN
		I := 1;
	  FOR I := 1 TO MIN DO
		BEGIN
			WRITELN (I,' - PRODUTO: ',PRODUTO[I].NOME, ' QUANTIDADE: ', PRODUTO[I].QUANTIDADE);
		END;
		WRITELN ('TECLE <ENTER>'); READKEY;
	END;	 
BEGIN	
	//MENU PRINCIPAL
	WHILE (FAZER <> 7) DO
	BEGIN
		CLRSCR;
		GOTOXY (33,1); WRITE ('MENU PRINCIPAL'); 
		GOTOXY (20,3); WRITE ('1 = CADASTRAR PRODUTO..................:');
		GOTOXY (20,5); WRITE ('2 = CONSULTAR PRODUTOS CADASTRADOS.....:');
		GOTOXY (20,7); WRITE ('3 = COMPRAR PRODUTO....................:');
		GOTOXY (20,9); WRITE ('4 = TOTAL DA COMPRA....................:');
		GOTOXY (20,11); WRITE ('5 = RECEBER............................:');
		GOTOXY (20,13); WRITE ('6 = VERIFICAR ESTOQUE..................:');
		GOTOXY (20,15); WRITELN ('7 = FINALIZAR..........................:');	
		READLN (FAZER);
		CLRSCR;
		CASE (FAZER) OF 
	   1: CADASTRO ;
	   2: CONSULTA ;
	   3: COMPRA ;
	   4: TOTALCOMPRA ;
	   5: TROCO ;
	   6: ESTOQUE ;
	   ELSE ;	
		END;
	END;
END.	 