Program LER_ARQUIVO_INTEIRO ;
USES
	CRT;
VAR
	ARQUIVO_INT : FILE OF INTEGER;
	NUMERO			: INTEGER;
	RESP				: CHAR;
Begin
	ASSIGN (ARQUIVO_INT, 'ARQINT.TXT');
	RESET(ARQUIVO_INT);
	RESP := 'S';
	WHILE NOT EOF (ARQUIVO_INT) DO
	BEGIN
		READ(ARQUIVO_INT, NUMERO);
		WRITELN(NUMERO);
	END;
	CLOSE(ARQUIVO_INT);
	READKEY;
End.