Program GRAVAR_RQUIVO_TEXTO ;
VAR
	ARQUIVO_TXT : TEXT;
	MENSAGEM	: STRING[50];
Begin
	ASSIGN (ARQUIVO_TXT, 'ARQTXT.TXT');
	APPEND (ARQUIVO_TXT);
	READLN(MENSAGEM);
	WRITELN(ARQUIVO_TXT ,MENSAGEM);
	CLOSE(ARQUIVO_TXT);

End.