Program LER_RQUIVO_TEXTO ;
VAR
	ARQUIVO_TXT : TEXT;
	MENSAGEM	: STRING[50];
Begin
	ASSIGN (ARQUIVO_TXT, 'ARQTXT.TXT');
	RESET (ARQUIVO_TXT);
	READLN(ARQUIVO_TXT , MENSAGEM);
	WRITELN(MENSAGEM);
	CLOSE(ARQUIVO_TXT);

End.