Program Exercicio_01 ;
VAR
NUM : INTEGER;
Begin
 WRITE ('DIGITE UM NUMERO INTEIRO E POSITIVO: ');
 READLN (NUM);
 IF (NUM MOD 2 = 0)
 THEN WRITELN ('ESTE NUMERO É POSITIVO!')
 ELSE WRITELN ('ESTE NUMERO É NEGATIVO!') ;
 READKEY  
End.