PROGRAM MODELO_05;
TYPE
		// REGISTRO DO CLIENTE
	REG_CAD = RECORD
							NOME: STRING;  // NOME, DATA, TEL, RUA, COMP, BAIRRO, CIDADE, ESTADO : STRING;
							DATA: STRING;  // CEP, NUMERO : INTEGER;
							TEL: STRING;   
							RUA: STRING;    
							NUMERO: INTEGER;    
							COMP: STRING;
							BAIRRO: STRING;
							CEP: INTEGER; 
							CIDADE: STRING;
							ESTADO: STRING;
						END;
						
		// REGISTRO DO EEQUIPAMENTO
	REG_EQUIP = RECORD
								EQUIP: STRING;
								MARCA: STRING;
								MODELO: STRING;
								NS: STRING;
								DEFEITO: STRING;
								CLIENTE: STRING;
								SOLUCAO: STRING;
							END;
		//VARIAVEIS GLOBAIS
VAR
	CADASTRO: ARRAY [1..100] OF REG_CAD;
	EQUIPAMENTO: ARRAY [1..100] OF REG_EQUIP;
	I, J, MAX, MAX_EQP : INTEGER;
	OPCAO : CHAR;
	
			//PROCEDIMENTO PARA CADASTRO DO CLEINTE
PROCEDURE CADASTRO_CLIENTE;
VAR OPCAO1 : CHAR;
BEGIN
  OPCAO1 := 'S';
	WHILE (OPCAO1 = 's') OR (OPCAO1 = 'S') DO
	BEGIN
		CLRSCR;
		MAX := MAX +1;
		GOTOXY (1,13); WRITE ('UTILIZE DATA NO FORMATO: DD/MM/AAAA');
		GOTOXY (1,14); WRITE ('CASO NÃO POSSUA COMPLEMENTO, COLOQUE UM ESPAÇO');
		FOR I := 1 TO 80 DO
		BEGIN
			GOTOXY (I,1); WRITE ('-');
			GOTOXY (I,11); WRITE ('-');
		END;
		GOTOXY(35,1); WRITELN ('CLIENTE');
		WRITE ('NOME: '); 
		READ (CADASTRO[MAX].NOME);
		CADASTRO[MAX].NOME := UPCASE (CADASTRO[MAX].NOME); 
		GOTOXY(40,2); WRITE (' DATA: ');
		READLN (CADASTRO[MAX].DATA);
		WRITELN ; 
		WRITE ('FONE: ');
		READLN (CADASTRO[MAX].TEL);
		WRITELN ; 
		WRITE ('ENDEREÇO: '); 
		READ (CADASTRO[MAX].RUA);
		CADASTRO[MAX].RUA := UPCASE (CADASTRO[MAX].RUA);
		GOTOXY (40,6); WRITE (' NUMERO: ');
		READ (CADASTRO[MAX].NUMERO);
		GOTOXY (55,6); WRITE (' COMPLEMENTO: '); 
		READLN (CADASTRO[MAX].COMP);
		CADASTRO[MAX].COMP := UPCASE (CADASTRO[MAX].COMP);
		WRITELN ; 
		WRITE ('BAIRRO: ');
		READ (CADASTRO[MAX].BAIRRO);
		CADASTRO[MAX].BAIRRO := UPCASE (CADASTRO[MAX].BAIRRO);
		GOTOXY (40,8); WRITE (' CEP: ');
		READ (CADASTRO[MAX].CEP);
		WRITELN;
		WRITE ('CIDADE: ');
		READ (CADASTRO[MAX].CIDADE);
		CADASTRO[MAX].CIDADE := UPCASE (CADASTRO[MAX].CIDADE);
		GOTOXY (40,10); WRITE (' ESTADO: ');
		READ (CADASTRO[MAX].ESTADO);
		CADASTRO[MAX].ESTADO := UPCASE (CADASTRO[MAX].ESTADO);
		GOTOXY (1,16); WRITELN('CONTINUAR CADASTRANDO S/N ?');
		READLN (OPCAO1)
	END;	
  GOTOXY (1,20); WRITELN ( 'TECLE <ENTER>', READKEY);
END;
			 //MOSTRAR OS CLIENTES CADASTRADOS
PROCEDURE AMOSTRAGEM_CLIENTE;
VAR Y, F : INTEGER;
BEGIN
	CLRSCR;
	F := 2;
	FOR I := 1 TO MAX DO
	BEGIN
		FOR J := 1 TO 80 DO
		BEGIN
			Y := MAX +3;
			GOTOXY (J,1); WRITE ('-');
			GOTOXY (J,Y); WRITE ('-');
		END;
		GOTOXY (1,F); WRITELN (I, ' - ', CADASTRO[I].NOME);
		F := F + 1;		
	END;
END;	
			//PROCESSO DE CONSULTA 
PROCEDURE CONSULTA_CLIENTE;
VAR CONS : INTEGER;
BEGIN
	IF (MAX >= 1) THEN
	BEGIN
		AMOSTRAGEM_CLIENTE;
		WRITE ('QUAL CADASTRO DESEJA CONSULTAR: ');
		READLN (CONS);
		CLRSCR;
		FOR I := 1 TO 80 DO
		BEGIN
			GOTOXY (I,1); WRITE ('-');
			GOTOXY (I,11); WRITE ('-');
		END;
		GOTOXY(35,1); WRITELN ('CLIENTE');
		WRITE ('NOME: '); 
		WRITE (CADASTRO[CONS].NOME); 
		GOTOXY(40,2); WRITE (' DATA: ');
		WRITELN (CADASTRO[CONS].DATA);
		WRITELN ; 
		WRITE ('FONE: ');
		WRITELN (CADASTRO[CONS].TEL);
		WRITELN ; 
		WRITE ('ENDEREÇO: '); 
		WRITE (CADASTRO[CONS].RUA);
		GOTOXY (40,6); WRITE (' NUMERO: ');
		WRITE (CADASTRO[CONS].NUMERO);
		GOTOXY (55,6); WRITE (' COMPLEMENTO: '); 
		WRITELN (CADASTRO[CONS].COMP);
		WRITELN ; 
		WRITE ('BAIRRO: ');
		WRITE (CADASTRO[CONS].BAIRRO);
		GOTOXY (40,8); WRITE (' CEP: ');
		WRITELN (CADASTRO[CONS].CEP);
		WRITELN;
		WRITE ('CIDADE: ');
		WRITE (CADASTRO[CONS].CIDADE);
		GOTOXY (40,10); WRITE (' ESTADO: ');
		WRITELN (CADASTRO[CONS].ESTADO);
		WRITELN;
		WRITELN ( 'TECLE <ENTER>', READKEY);
	END ELSE
	WRITE  ('PARA CONSULTAR É NECESSARIO CADASTRAR!', READKEY);	
END;

    //PROCEDIMENTO PARA CADASTRO DO EQUIPAMENTO
PROCEDURE CADASTRO_EQUIPAMENTO;
VAR CAD : INTEGER;
		OPCAO1 : CHAR;
BEGIN
	IF (MAX >= 1) THEN
	BEGIN 
		CLRSCR;
		AMOSTRAGEM_CLIENTE;
		WRITE ('PARA QUAL CLIENTE DESEJA CADASTRAR UM EQUIPAMENTO? ');
		READ (CAD);
		CLRSCR;
		MAX_EQP := MAX_EQP+1;
		FOR I := 1 TO 80 DO
		BEGIN
			GOTOXY (I,1); WRITE ('-');
			GOTOXY (I,7); WRITE ('-');
		END;
		GOTOXY(35,1); WRITELN ('EQUIPAMENTO');
		WRITE ('EQUIPAMENTO: '); 
		READ (EQUIPAMENTO[MAX_EQP].EQUIP);
		EQUIPAMENTO[MAX_EQP].EQUIP := UPCASE (EQUIPAMENTO[MAX_EQP].EQUIP); 
		GOTOXY(40,2); WRITE ('MARCA: ');
		READLN (EQUIPAMENTO[MAX_EQP].MARCA);
		EQUIPAMENTO[MAX_EQP].MARCA := UPCASE (EQUIPAMENTO[MAX_EQP].MARCA);
		WRITELN ; 
		WRITE ('MODELO: ');
		READ (EQUIPAMENTO[MAX_EQP].MODELO);
		EQUIPAMENTO[MAX_EQP].MODELO := UPCASE (EQUIPAMENTO[MAX_EQP].MODELO);
		GOTOXY (40,4); WRITE ('NS: '); 
		READLN (EQUIPAMENTO[MAX_EQP].NS);
		EQUIPAMENTO[MAX_EQP].NS := UPCASE (EQUIPAMENTO[MAX_EQP].NS);
		WRITELN ; 
	  WRITE ('DEFEITO: ');
		READ (EQUIPAMENTO[MAX_EQP].DEFEITO);		
		EQUIPAMENTO[MAX_EQP].DEFEITO := UPCASE (EQUIPAMENTO[MAX_EQP].DEFEITO);
		EQUIPAMENTO[MAX_EQP].CLIENTE := CADASTRO[CAD].NOME;
		EQUIPAMENTO[MAX_EQP].SOLUCAO := 'EM ANALISE';	
	  GOTOXY (1,8); WRITELN ( 'TECLE <ENTER>', READKEY);
	END ELSE
	WRITE  ('PARA CADASTRAR EQUIPAMENTO É NECESSARIO CADASTRAR CLIENTE!', READKEY);
END;

				//MOSTRAR OS EQUIPAMENTOS CADASTRADOS
PROCEDURE AMOSTRAGEM_EQUIPAMENTO;
VAR Y, F : INTEGER;
BEGIN
	CLRSCR;
	F := 2;
	FOR I := 1 TO MAX_EQP DO
	BEGIN
		FOR J := 1 TO 80 DO
		BEGIN
			Y := MAX_EQP +3;
			GOTOXY (J,1); WRITE ('-');
			GOTOXY (J,Y); WRITE ('-');
		END;
		GOTOXY (1,1); WRITE ('EQUIPAMENTO');
		GOTOXY (25,1); WRITE ('MARCA');
		GOTOXY (40,1); WRITE ('CLIENTE');
		GOTOXY (1,F); WRITE (I, ' - ', EQUIPAMENTO[I].EQUIP);
		GOTOXY (23,F); WRITE ('| ', EQUIPAMENTO[I].MARCA);
		GOTOXY (38,F); WRITE ('| ', EQUIPAMENTO[I].CLIENTE);
		F := F + 1;		
	END;
END;

			//CONSULTA DOS EQUIPAMENTOS
PROCEDURE CONSULTA_EQUIPAMENTO;
VAR CONS : INTEGER;
BEGIN
	IF (MAX_EQP >= 1) THEN
	BEGIN
		AMOSTRAGEM_EQUIPAMENTO;
		WRITELN;
		WRITE ('QUAL EQUIPAMENTO DESEJA CONSULTAR? ');
		READ (CONS);
		CLRSCR;
		FOR I := 1 TO 80 DO
		BEGIN
			GOTOXY (I,1); WRITE ('-');
			GOTOXY (I,9); WRITE ('-');
		END;
		GOTOXY(35,1); WRITELN ('EQUIPAMENTO');
		WRITE ('EQUIPAMENTO: ', EQUIPAMENTO[CONS].EQUIP); 
		GOTOXY(40,2); WRITELN (' MARCA: ', EQUIPAMENTO[CONS].MARCA);
		WRITELN ; 
		WRITE ('MODELO: ', EQUIPAMENTO[CONS].MODELO);
		GOTOXY (40,4); WRITELN ('NS: ', EQUIPAMENTO[CONS].NS); 
		WRITELN ; 
	  WRITE ('DEFEITO: ', EQUIPAMENTO[CONS].DEFEITO);
		GOTOXY (40,6); WRITELN('SOLUÇÃO: ', EQUIPAMENTO[CONS].SOLUCAO);
		WRITELN ; 		
		WRITE ('CLIENTE: ', EQUIPAMENTO[CONS].CLIENTE);		
	  GOTOXY (1,13); WRITELN ( 'TECLE <ENTER>', READKEY);
	END ELSE
	WRITE  ('PARA CONSULTAR É NECESSARIO CADASTRAR!', READKEY);
END;
			//ADICIONAR UMA SOLUÇÃO PARA OS EQUIPAMENTOS
PROCEDURE SOLUCAO;
VAR CONS : INTEGER;
BEGIN
	IF (MAX_EQP >= 1) THEN
	BEGIN
		AMOSTRAGEM_EQUIPAMENTO;
		WRITELN;
		WRITE ('QUAL EQUIPAMENTOI DESEJA COLOCA A SOLUÇÃO? ');
		READLN (CONS);
		CLRSCR;
		FOR I := 1 TO 80 DO
		BEGIN
			GOTOXY (I,1); WRITE ('-');
			GOTOXY (I,3); WRITE ('-');
		END;
		GOTOXY(35,1); WRITELN ('SOLUÇÃO');
		GOTOXY (1,2); WRITE ('SOLUÇÃO: ');
		READ (EQUIPAMENTO[CONS].SOLUCAO);
		EQUIPAMENTO[CONS].SOLUCAO := UPCASE (EQUIPAMENTO[CONS].SOLUCAO);
		GOTOXY (1, 6); WRITELN ( 'TECLE <ENTER>', READKEY);
	END ELSE
	WRITE  ('PARA ADICIONAR UMA SOLUÇÃO É NECESSARIO CADASTRAR!', READKEY);		
END;	
			//CORPO DO PRROGRAMA PRINCIPAL (MAIN)
BEGIN
	TEXTCOLOR(WHITE);
	WHILE (OPCAO <> '6') DO
	BEGIN
		CLRSCR;
		FOR I := 1 TO 40 DO
			WRITE ('-');
		GOTOXY(13,1); WRITELN ('MENU PRINCIPAL');
		WRITELN (' 1 - CADASTRAR UM CLIENTE');
		WRITELN (' 2 - CONSULTAR CLIENTES');
		WRITELN (' 3 - CADASTRAR UM EQUIPAMENTO');
		WRITELN (' 4 - CONSULTAR EQUIPAMENTOS');
		WRITELN (' 5 - INCLUIR SOLUÇÃO PARA UM EQUIPAMENTO');
		WRITELN (' 6 - FINALIZAR');
		FOR I := 1 TO 40 DO
			WRITE ('-'); 
		WRITELN (' ');
		WRITELN ('ESCOLHA UMA OPÇÃO');
		READLN (OPCAO);
		CASE (OPCAO) of 
	    '1': CADASTRO_CLIENTE ;
	    '2': CONSULTA_CLIENTE ;
	    '3': CADASTRO_EQUIPAMENTO ;
	    '4': CONSULTA_EQUIPAMENTO;
	    '5': SOLUCAO; 
	    '6': WRITELN ( 'TECLE <ENTER>', READKEY);
	    ELSE 
	    WRITELN ('OPÇÃO INVALIDA, ESCOLHA ENTRE 1 E 6');
	    WRITELN ( 'TECLE <ENTER>', READKEY);
  	END;
	END;
END.					